on:
  workflow_dispatch:
name: npm-audit
jobs:
  findPackages:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.nodePaths }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 18
      - id: interrogate
        run: node ./.github/workflows/list-node-paths-for-deps.js
  updateDeps:
    runs-on: ubuntu-latest
    needs: findPackages
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        package: ${{fromJson(needs.findPackages.outputs.nodePaths)}}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 18
      - run: echo ./packages/${{ matrix.package }}
      - run: cd ./packages/${{ matrix.package }} && npm audit fix
        continue-on-error: true
      - uses: googleapis/code-suggester@589b3ac11ac2575fd561afa45034907f301a375b # v4
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: googleapis
          upstream_repo: repo-automation-bots
          description: 'ran `npm audit fix` in packages/${{ matrix.package }}'
          title: 'chore: update lock file for ${{ matrix.package }}'
          message: 'chore: update lock file for ${{ matrix.package }}'
          branch: update-lock-file-${{ matrix.package }}
          primary: main
          force: true
          git_dir: '.'
